const VALIDATION_CODE_ERROR = 400;
const UNAUTH_CODE_ERROR = 401;
const FORBIDDEN_CODE_ERROR = 403;
const NOTFOUND_CODE_ERROR = 404;
const CONFLICT_CODE_ERROR = 409;
const SERVER_CODE_ERROR = 500;

module.exports = {
  VALIDATION_CODE_ERROR,
  UNAUTH_CODE_ERROR,
  FORBIDDEN_CODE_ERROR,
  NOTFOUND_CODE_ERROR,
  CONFLICT_CODE_ERROR,
  SERVER_CODE_ERROR,
};
